name: PH-OS Build S8

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential curl flex git libelf-dev libssl-dev python3 libncurses5-dev gcc-aarch64-linux-gnu

      - name: Clone
        run: git clone --depth=1 https://github.com/exynos8895/android_kernel_samsung_universal8895.git kernel

      - name: Build
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # 1. Конфиг
          make exynos8895-dreamlte_defconfig
          
          # 2. ЖЕСТКИЙ ФИКС (вырезаем причину Error 2 на 1-й минуте)
          sed -i 's/YYLTYPE yylloc;/extern YYLTYPE yylloc;/g' scripts/dtc/dtc-lexer.lex.c_shipped || true
          sed -i 's/YYLTYPE yylloc;/extern YYLTYPE yylloc;/g' scripts/dtc/dtc-parser.tab.c || true
          find . -name "Makefile*" -type f -exec sed -i 's/-Werror//g' {} + || true
          
          # 3. ВАРКА
          make -j$(nproc) KCFLAGS="-w -fcommon" HOSTCFLAGS="-w -fcommon"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Developer-Edition-Kernel
          path: kernel/arch/arm64/boot/Image.gz-dtb





























      

        


